name: Benchmark

on:
  - push

env:
  BENCHMARK_LAUNCHES: 100
  BENCHMARK_MAX_STDEV: 10
  BENCHMARK_RETRIES: 3

jobs:
  product:
    name: Product benchmark
    concurrency:
      group: ${{ github.workflow }}-benchmark-product-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    env:
      BENCHMARK_TYPE: product
      BENCHMARK_OPTIONS: '{}'
    steps:
      - name: Setup repository
        uses: actions/checkout@v3
      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Compile sources
        run: npm run compile
      - name: Benchmark (async)
        run: npm run bench-async
      - name: Benchmark (stream)
        run: npm run bench-stream
      - name: Benchmark (sync)
        run: npm run bench-sync

  regress:
    name: Regress benchmark with options (${{ matrix.benchmark_options }})
    concurrency:
      group: ${{ github.workflow }}-benchmark-regress-${{ matrix.benchmark_options }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        benchmark_options:
          - '{}'
          - '{ "objectMode": true }'
          - '{ "absolute": true }'
    env:
      BENCHMARK_TYPE: regression
      BENCHMARK_OPTIONS: ${{ matrix.benchmark_options }}
    steps:
      - name: Setup repository
        uses: actions/checkout@v3
      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Compile sources
        run: npm run compile
      - name: Benchmark (async)
        run: npm run bench-async
      - name: Benchmark (stream)
        run: npm run bench-stream
      - name: Benchmark (sync)
        run: npm run bench-sync
